### ISSUE TITLE
Question about the viewpoint candidates and selection.

### ISSUE THREAD

**Issue by johnnylu305** [KingteeLoki-Ran/NeurAR#1]
Hi, thank you for the great work. After reading the paper, I have a few questions about it. It would be great if you can help me figure them out.

1. On page 5, you mentioned the way to sample candidates. "For the view planning, we introduce a prior of objects in the center of the space for the candidate viewpoint sampling: ..." Do you sample the candidates uniformly from the surface of the bounding sphere? Can you provide more explanation about it?

2. How do you choose the final destination for RRT* from the sample candidates above? 

3. On page 5, you mentioned that "the optimization receives one or two images collected on the view path from cameras." Given a camera path from RRT*, how do you choose one or two viewpoints? Do you sample viewpoints along the path and choose the most significant variance one? 

Looking forward to your help. Thank you.

**Comment by KingteeLoki-Ran** [comment]
Thank you for your attention:
1 & 2. For NeurAR itself, candidates are first randomly sampled within a certain surface range (radius), and then the final candidate is determined based on the uncertainty of each candidate.
3. Select according to a fixed length on the path, for example, select a viewpoint angle every 2m.
Hope the answer can help you. Thank you.

**Comment by johnnylu305** [comment]
Hi, thank you for the explanation. I have one follow-up question about my first question. 

Because you mention "within a certain surface range", do you construct two bounding spheres and sample viewpoints between them so that you can avoid the illegal viewpoints (e.g., the viewpoint inside the object)?

Thanks.

**Comment by KingteeLoki-Ran** [comment]
Hi johnnylu305:

as described on Page 5 "The camera moves in a band with the nearest distance to the object Dnear meters and the farthest distance Dfar meters". When selecting candidate perspectives, we use the previous NBV as the center point and randomly sample candidates within the radius R. While satisfying constraint R, the band constraint needs to be satisfied.

Thanks

**Comment by johnnylu305** [comment]
Got it. Thanks
